stages:
  - prepare
  - classify

variables:
  GIT_SUBMODULE_STRATEGY: none

default:
  image: python:3.12
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - .venv

install_dependencies:
  stage: prepare
  interruptible: true
  script:
    - git config --global credential.helper store
    - git credential approve < <(echo "protocol=https\nhost=github.com\nusername=$GITHUB_USER_NAME\npassword=$GITHUB_ACCESS_TOKEN")
    - make init
  cache:
    policy: push

romance:
  stage: classify
  script:
    - make classify CONFIG=datasets/Romance/config/romance_config.yml
  artifacts:
    paths:
      - datasets/Romance/experiments

germanic:
  stage: classify
  script:
    - make classify CONFIG=datasets/Germanic/config/germanic_config.yml
  artifacts:
    paths:
      - datasets/Germanic/experiments

slavic:
  stage: classify
  script:
    - make classify CONFIG=datasets/Slavic/config/slavic_config.yml
  artifacts:
    paths:
      - datasets/Slavic/experiments
