stages:
  - prepare
  - classify

variables:
  GIT_SUBMODULE_STRATEGY: none

default:
  image: python:3.12
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - .venv

install_dependencies:
  stage: prepare
  interruptible: true
  script:
    - git config --global credential.helper store
    - |
      git credential approve <<EOF
      protocol=https
      host=github.com
      username=${GITHUB_USER_NAME}
      password=${GITHUB_ACCESS_TOKEN}
      EOF
    - make init
  cache:
    policy: push

romance:
  stage: classify
  script:
    - make classify-romance
  artifacts:
    paths:
      - datasets/Romance/experiments

germanic:
  stage: classify
  script:
    - make classify-germanic
  artifacts:
    paths:
      - datasets/Germanic/experiments

slavic:
  stage: classify
  script:
    - make classify-slavic
  artifacts:
    paths:
      - datasets/Slavic/experiments
