family:
    name: Slavic
    file: datasets/Slavic/data/slavic_data.tsv
    min_amc: 0.68
    exclude: ['Čakavian (Istria)', 'Čakavian (Cres)', 'Čakavian (Burgenland)', 'Kajkavian', 'Lithuanian', 'Latvian']
    outdir: datasets/Slavic/

transcription:
    global:
        ignore_stress: false
        combine_diphthongs: true
        normalize_geminates: false
        #suprasegmentals: ['ˀ', '̂', '̌', '̀', '́', '̄', 'ˈ']
        #level_suprasegmentals: 'ˈ'

phon_corr:
    phon_env: false
    refresh: []
    refresh_all: true

cluster:
    cognates: none

# evaluation:
#     precalculated_word_scores: 

tree:
    linkage: nj
    root: Proto-Slavic
    reference: [
        "datasets/Slavic/trees/ref/reference_001.tre"
    ]