family:
    name: Romance
    file: datasets/Romance/data/romance_data.tsv
    min_amc: 0.7
    exclude: ['Dalmatian', 'Istriot', 'Savoyard', 'Istro-Romanian']
    outdir: datasets/Romance/

experiment:
  name: ""

transcription:
    global:
        ignore_stress: false
        combine_diphthongs: true
        normalize_geminates: true

phon_corr:
    phon_env: false
    refresh: []
    refresh_all: true

cluster:
    cognates: none

evaluation:
    similarity: gradient
    method: hybrid
    pmi_weight: 0
    surprisal_weight: 0.5
    phon_weight: 1
    normalize_weights: false
    n_samples: 10
    sample_size: 0.8
    calibrate: false
    min_similarity: 0

tree:
    linkage: nj
    root: Latin
    reference: [
        "datasets/Romance/trees/ref/reference_001.tre",
        "datasets/Romance/trees/ref/reference_002.tre",
    ]
