family:
    name: Romance
    file: /Users/philip.georgis/Documents/Projects/LinguisticPhylogenetics.nosync/Datasets/Romance/data/romance_data.tsv
    min_amc: 0.7
    exclude: ['Dalmatian', 'Istriot', 'Savoyard', 'Istro-Romanian', "Old French"]
    outdir: /Users/philip.georgis/Documents/Projects/LinguisticPhylogenetics.nosync/Datasets/Romance/

experiment:
  name: ""

transcription:
    global:
        ignore_stress: false
        combine_diphthongs: true
        normalize_geminates: true

pmi:
    min_corr: 2
    refresh: []
    refresh_all_pmi: true

surprisal:
    ngram: 1
    min_corr: 2
    phon_env: true 
    refresh: []
    refresh_all_surprisal: true

cluster:
    cognates: none

evaluation:
    similarity: gradient
    method: hybrid
    pmi_weight: 0
    surprisal_weight: 4
    phon_weight: 1
    n_samples: 10
    sample_size: 0.8
    calibrate: false
    min_similarity: 0

tree:
    linkage: nj
    newick: true
