family:
    include: ['Latin', 'Sicilian', 'Italian', 'Venetian', 'Eastern Lombard', 'French']

experiment:
    name: "test-minimal"

config:
    extend: "datasets/Romance/config/test_config_full.yml"
