family:
    include: ['Proto-Balto-Slavic', 'Proto-Slavic', 'Slovenian', 'Ukrainian', 'Štokavian', 'Upper Sorbian']

experiment:
    name: "test-minimal"

config:
    extend: "datasets/BaltoSlavic/config/test_config_full.yml"
