family:
  name:
  # file: path/to/input/file
  min_amc: 0.65 # TODO 0.7?
  exclude: []
  # outdir: path/to/outdir

transcription:
    global:
        asjp: false
        ignore_stress: false
        combine_diphthongs: true
        normalize_geminates: false
        preaspiration: true
        suprasegmentals: 
        level_suprasegmentals: 
        ch_to_remove: {' '}
    # doculects:
    #     French:
    #         ignore_stress: true
    #     Italian:
    #         normalize_geminates: true

pmi:
  refresh: []
  refresh_all_pmi: false

surprisal:
  ngram: 1
  phon_env: true 
  refresh: []
  refresh_all_surprisal: false

cluster:
  cognates: auto
  method: hybrid
  cluster_threshold: 0.5

evaluation:
  similarity: gradient
  method: hybrid
  pmi_weight: 0.25
  surprisal_weight: 0.5
  phon_weight: 0.25
  n_samples: 10
  sample_size: 0.8
  exclude_synonyms: true
  calibrate: true
  min_similarity: 0

tree:
  linkage: nj
  newick: true # TODO change default to true in phyloLing.py