family:
    include: ['Old Chinese', 'Jin', 'Shanghainese', 'Taiwanese Hokkien', 'Fuzhounese']

experiment:
    name: "test-minimal"

config:
    extend: "datasets/Sinitic/config/test_config_full.yml"
