family:
    name: Germanic
    file: datasets/Germanic/data/germanic_data.tsv
    min_amc: 0.65
    exclude: ['Old English', 'Old Norse', 'Mainland North Frisian']
    outdir: datasets/Germanic/

experiment:
  name: ""

transcription:
    global:
        ignore_stress: false
        combine_diphthongs: true
        normalize_geminates: true
        ch_to_remove: ['̩']
    # doculects:
    #     "Swiss German":
    #         normalize_geminates: false
    #     Danish:
    #         suprasegmentals: ['ˀ']

phon_corr:
    phon_env: false
    refresh: []
    refresh_all: true

cluster:
    cognates: none

# evaluation:
#     precalculated_word_scores: 

tree:
    linkage: nj
    root: Proto-Germanic
    reference: [
        "datasets/Germanic/trees/ref/reference_001.tre"
    ]