family:
    name: Germanic
    file: datasets/Germanic/data/germanic_data.tsv
    exclude: ['Plautdietsch', 'Old Dutch', 'Middle Dutch', 'Old Saxon', 'Middle Low German', 'Australian English']
    outdir: datasets/Germanic/

experiment:
  name: ""

transcription:
    global:
        ignore_stress: false
        combine_diphthongs: true
        normalize_geminates: true
        ch_to_remove: ['̩']
    doculects:
        "American English":
            normalize_geminates: false
        English:
            normalize_geminates: false
        Scots:
            normalize_geminates: false
        Westphalian:
            normalize_geminates: false
        Eastphalian:
            normalize_geminates: false
        Mecklenburgisch-Vorpommersch:
            normalize_geminates: false
        "East Frisian Low Saxon":
            normalize_geminates: false
        "Northern Low Saxon":
            normalize_geminates: false

phon_corr:
    phon_env: true
    refresh: []
    refresh_all: true

# cognates:
#     cluster_threshold: 

# evaluation:
#     precalculated_word_scores: 

tree:
    root: Proto-Germanic
    reference: [
        "datasets/Germanic/trees/ref/reference_001.tre"
    ]
