family:
    name: Germanic
    file: datasets/Germanic/data/germanic_data.tsv
    exclude: ['Old English', 'Old West Norse', 'Plautdietsch']
    outdir: datasets/Germanic/

experiment:
  name: ""

transcription:
    global:
        ignore_stress: false
        combine_diphthongs: true
        normalize_geminates: false
        ch_to_remove: ['̩']
    doculects:
        Proto-Germanic:
            normalize_geminates: true
        Gothic:
            normalize_geminates: true
        Icelandic:
            normalize_geminates: true
        Faroese:
            normalize_geminates: true
        "Nynorsk Norwegian":
            normalize_geminates: true
        "Bokmål Norwegian":
            normalize_geminates: true
        Elfdalian:
            normalize_geminates: true
        Swedish:
            normalize_geminates: true
        "Swiss German":
            normalize_geminates: true

phon_corr:
    refresh: []
    refresh_all: true

# cognates:
#     cluster_threshold: 1.41 #1.366

# evaluation:
#     precalculated_word_scores: 

tree:
    root: Proto-Germanic
    reference: [
        "datasets/Germanic/trees/ref/reference_001.tre"
    ]
