family:
    name: Germanic
    file: datasets/Germanic/data/germanic_data.tsv
    exclude: ['Old English', 'Old West Norse', 'East Frisian Low Saxon']
    outdir: datasets/Germanic/

experiment:
  name: ""

transcription:
    global:
        ignore_stress: false
        combine_diphthongs: true
        normalize_geminates: true
        ch_to_remove: ['̩']
    # doculects:
    #     "Swiss German":
    #         normalize_geminates: false
    #     Danish:
    #         suprasegmentals: ['ˀ']

phon_corr:
    refresh: []
    refresh_all: true

# evaluation:
#     precalculated_word_scores:

tree:
    root: Proto-Germanic
    reference: [
        "datasets/Germanic/trees/ref/reference_001.tre"
    ]