family:
    name: Germanic
    file: /Users/philip.georgis/Documents/Projects/LinguisticPhylogenetics/Datasets/Germanic/germanic_data.tsv
    min_amc: 0.65
    exclude: ['Old English', 'Old Norse']
    outdir: /Users/philip.georgis/Documents/Projects/LinguisticPhylogenetics/Datasets/Germanic/

transcription:
    global:
        ignore_stress: false
        combine_diphthongs: true
        normalize_geminates: true
        ch_to_remove: ['̩']
    # doculects:
    #     "Swiss German":
    #         normalize_geminates: false
    #     Danish:
    #         suprasegmentals: ['ˀ']

pmi:
    refresh: []
    refresh_all_pmi: true

surprisal:
    ngram: 1
    phon_env: true 
    refresh: []
    refresh_all_surprisal: true

cluster:
    cognates: none

evaluation:
    similarity: gradient
    method: composite
    pmi_weight: 1.5
    surprisal_weight: 2
    phon_weight: 1
    n_samples: 10
    sample_size: 0.8
    calibrate: true
    min_similarity: 0

tree:
    linkage: nj
    newick: true
