family:
    include: ['Proto-Germanic', 'Old West Norse', 'Nynorsk Norwegian', 'Mainland North Frisian', 'Middle High German']

experiment:
    name: "test-minimal"

config:
    extend: "datasets/Germanic/config/test_config_full.yml"
