family:
  name:
  # file: path/to/input/file
  min_amc: 0.65 # TODO 0.7?
  include: []
  exclude: []
  # outdir: path/to/outdir

experiment:
  name: 

transcription:
    global:
        asjp: false
        ignore_stress: false
        combine_diphthongs: true
        normalize_geminates: false
        preaspiration: true
        suprasegmentals: 
        level_suprasegmentals: 
        ch_to_remove: {' '}
        min_phone_instances: 2
    # doculects:
    #     French:
    #         ignore_stress: true
    #     Italian:
    #         normalize_geminates: true

alignment:
  gap_ch: '-' # alternative null character <∅> looks too similar to IPA character <ø>
  pad_ch: '#'

phon_corr:
  n_samples: 3
  sample_size: 0.8
  min_corr: 2
  ngram: 1
  phon_env: true 
  refresh: []
  refresh_all: false

cluster:
  cognates: auto
  method: hybrid
  cluster_threshold: 0.5

evaluation:
  similarity: gradient
  method: composite
  pmi_weight: 1.5
  surprisal_weight: 2
  phon_weight: 1
  normalize_weights: false
  n_samples: 10
  sample_size: 0.8
  exclude_synonyms: true
  calibrate: true
  min_similarity: 0
  precalculated_word_scores: 

tree:
  linkage: nj
  root: